name: Your CICD Pipeline Name
on: [push]
jobs:
  myjob:
    runs-on: Nexus001.4TheLulz
    steps:
    - uses: actions/checkout@v2
    - name: Auto Deploy On GCP - Getting the images from registry
      run: printf "Hello, World!!\n" && uname -a && hostname -f && pwd && bash /home/ox1d0/Downloads/Brightcove/RestWeb001/AutoDeployOnGCP001.bash
